# Generated by Django 5.1.4 on 2025-01-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesoriu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriere', models.TextField()),
                ('compatibilitate', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Accesorii',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('biografie', models.TextField()),
                ('tara', models.CharField(max_length=100)),
                ('an_formare', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Artiști',
            },
        ),
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Genuri',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriere', models.TextField()),
                ('stare', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Instrumente',
            },
        ),
        migrations.CreateModel(
            name='Stoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produs_id', models.IntegerField()),
                ('tip_produs', models.CharField(choices=[('album', 'Album'), ('instrument', 'Instrument'), ('accesoriu', 'Accesoriu')], max_length=50)),
                ('cantitate', models.IntegerField()),
                ('locatie_depozit', models.CharField(max_length=200)),
                ('ultima_actualizare', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stocuri',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('data_lansare', models.DateField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriere', models.TextField()),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='albume/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.artist')),
                ('gen', models.ManyToManyField(to='magazin.gen')),
            ],
            options={
                'verbose_name_plural': 'Albume',
            },
        ),
        migrations.CreateModel(
            name='Melodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('durata', models.DurationField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.album')),
            ],
            options={
                'verbose_name_plural': 'Melodii',
            },
        ),
    ]
