# Generated by Django 5.1.4 on 2025-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stoc',
            options={},
        ),
        migrations.AlterField(
            model_name='stoc',
            name='cantitate',
            field=models.IntegerField(default=0),
        ),
    ]
