# Generated by Django 5.1.4 on 2025-01-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_alter_stoc_options_alter_stoc_cantitate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('vizualizeaza_oferta', 'Poate vizualiza ofertele speciale')]},
        ),
    ]
