# Generated by Django 5.1.4 on 2025-01-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stoc',
            options={'verbose_name_plural': 'Stocuri'},
        ),
        migrations.AddIndex(
            model_name='stoc',
            index=models.Index(fields=['tip_produs', 'produs_id'], name='magazin_sto_tip_pro_ce9861_idx'),
        ),
    ]
